services:
  database:
    image: ${POSTGRES_DOCKER_IMAGE}
    restart: always
    environment:
        POSTGRES_DB: todo-service
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
